version: "3"
services:
  app:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.111.12
    container_name: jfrog-app
    hostname: jfrog-app
    volumes:
      - /volumes/jfrog/app:/var/opt/jfrog/artifactory
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 8082:8082
      - 5000:5000
    networks:
      - internal
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000        
networks:
  internal:
    external: true
